Appium Priority Two Functionality
flagpolejs/flagpole pull request #174
Opened 2021-11-18 19:12 UTC by ncalaway

This adds the priority two functionality and documentation to the range of things Flagpole can do with Appium.

2021-11-20 04:20 UTC, jasonbyrne requested changes

2021-11-20 04:20 UTC, jasonbyrne commented on docs/setup.md
> +    }, {
I'm not a fan of this fourth property. I would make it part of the third argument but as a sub-property

2021-11-20 04:20 UTC, jasonbyrne commented on docs/appiumresponse.md
> +### setImplicitWait(ms: number): Promise<void>
Really nervous about making too many things that are on-off

2021-11-20 04:20 UTC, jasonbyrne commented on src/appium/appium-helpers.ts
> +  devProperties: DeviceProperties = {}
Let's do this differently

2021-11-22 14:50 UTC, ncalaway commented on docs/setup.md
> +    }, {
Done

2021-11-22 14:51 UTC, ncalaway commented on src/appium/appium-helpers.ts
> +  devProperties: DeviceProperties = {}
Done

2021-11-22 14:52 UTC, ncalaway commented on docs/appiumresponse.md
> +### setImplicitWait(ms: number): Promise<void>
I wanted to expose this as a public method since it's something every other Appium driver lets you do. I thought it would be okay since I put it on just the Appium response.

If you prefer, I can turn this into a private method that a couple of our explicit wait calls use. Would that be better?

2021-11-23 22:03 UTC, jasonbyrne commented on docs/appiumresponse.md
> +### setImplicitWait(ms: number): Promise<void>
Yeah, what I want to try to do is come up with as much standard across all types as we can. Not every method makes sense to every scenario... but i don't want every type of scenario just to be its own little world. that defeats the purpose of a cohesive thing.

2021-11-24 14:36 UTC, ncalaway commented on docs/appiumresponse.md
> +### setImplicitWait(ms: number): Promise<void>
Okay I made the getting and setting of implicit waits private.

2021-12-03 14:58 UTC, ncalaway commented on tests/src/visual.ts
>      await context.waitForExists("img[alt='Debian']");
Using debian.org here since it doesn't change nearly as frequently as Google does. It also has a PNG logo that we could use once the issue with .`download()` is sorted.

2021-12-07 14:48 UTC, jasonbyrne approved these changes

2021-12-07 15:01 UTC, merged