Changed body of HttpResponse to any
flagpolejs/flagpole pull request #187
Opened 2021-12-06 16:14 UTC by ncalaway

Having the body of every HttpResponse was corrupting images I tried to download. I don't know if anything will break by not forcing every HttpResponse.body to be a string, but this certainly fixes downloading images. Text downloaded is still represented as a string.

2021-12-06 21:23 UTC, jasonbyrne requested changes

2021-12-06 21:23 UTC, jasonbyrne commented on src/value.ts
> +      if (resp.trailers["content-type"].split("/")[0] === "image") {
This seems out of place here inside the `if (localFilePath) {` feels like it should be part of line 767 instead.

I'm also uncertain about changing the return type here from HttpResponse to the response body. Something might be relying on the rest of the response

2021-12-06 21:23 UTC, jasonbyrne commented on src/httpresponse.ts
> +    response.trailers["content-type"] = contentType;
I'm curious why we need to use trailers here instead of the header.

2021-12-06 21:23 UTC, jasonbyrne commented on tests/src/visual.ts
> +      "/Users/nick/Documents/GitHub/flagpole/tests/images/debian.png"
We should make this a relative path that is not absolute to your machine

2021-12-07 14:45 UTC, jasonbyrne requested changes

2021-12-07 14:45 UTC, jasonbyrne commented on src/httpresponse.ts
> +          : contentType?.split("/")[0] === "image"
this would be more readable as `contentType.startsWith('image')`

2021-12-07 14:45 UTC, jasonbyrne commented on src/value.ts
> +    }
I don't like setting something and then immediately resetting it if we don't have to do that. 

```
const file: string | Buffer = resp.headers["content-type"].startsWith("image") ?  
   Buffer.from(resp.body, "base64") : resp.body;
```

would be cleaner

2021-12-07 14:45 UTC, jasonbyrne commented on src/value.ts
> +    return file;
I'm still confused why we are returning the file contents here instead of the response like before

2021-12-07 14:59 UTC, ncalaway commented
@jasonbyrne 
> I'm still confused why we are returning the file contents here instead of the response like before

I'm doing this because of the testing code here:
```suite
  .html("Cheerio test of Google Logo")
  .open("/")
  .next("Logo", async (context) => {
    // ✕  Logo should look like the control.
    //  …  Actual: Error: Input image is invalid.
    // const logo = await context.exists("img[alt='Google']");
    // context
    //   .assert("Logo should look like the control.", await logo.download())
    //   .looksLike("@google");
  });
```

It's trying to do a looksLike assertion on an HttpResponse, which wouldn't work.

We could return the HttpResponse and call the assertion on HttpResponse.body, but that would not work with images because it has to be a string. If we could allow HttpResponse.body to be a string and a buffer, we could keep returning the HttpResponse. I probably wouldn't even have to bother with the base64 encoding/decoding if we did that.

2021-12-07 16:48 UTC, ncalaway commented
@jasonbyrne per our discussion on Slack, I restored iValue.download() to its previous functionality and added logic for iAssertion.looksLike() to handle HttpResponse objects.

2021-12-15 03:33 UTC, jasonbyrne approved these changes

2021-12-15 03:33 UTC, merged