Appium double tap
flagpolejs/flagpole pull request #192
Opened 2021-12-07 15:04 UTC by ncalaway

Double taps in the midpoint of an element

2021-12-07 15:24 UTC, ncalaway commented
This is a candidate for standardization. We may want to be able to double tap elements in browser testing. Thoughts?

2021-12-07 18:25 UTC, ncalaway commented
Already added to interface.

2021-12-13 15:54 UTC, kbabcock1 approved these changes

2021-12-13 15:56 UTC, jasonbyrne requested changes

2021-12-13 15:56 UTC, jasonbyrne commented on src/appium/appiumelement.ts
> +    if (!boundsRes) return "Error: element bounds not acquired";
Should throw, return text seems odd

2021-12-14 19:18 UTC, jasonbyrne approved these changes

2021-12-14 19:34 UTC, merged