Added ability to get page source
flagpolejs/flagpole pull request #195
Opened 2021-12-07 15:07 UTC by ncalaway

Get XML page source for current viewport. Useful as a helper method for scrolling until an element is present or until scrolling cannot be done anymore.

2021-12-07 15:23 UTC, ncalaway commented
This is a candidate for standardization. We may want to be able to get the entire page source for HTML testing, or the current viewport source for browser testing, if possible. Thoughts?

2021-12-13 16:00 UTC, kbabcock1 approved these changes

2021-12-13 16:00 UTC, jasonbyrne requested changes
I'm uneasy with this `iValue | Promise<iValue>` because it hurts intellisense and likely breaks old IDEs

2021-12-14 19:22 UTC, jasonbyrne reviewed
Wanna make this return ValuePromise instead?

2021-12-14 19:30 UTC, jasonbyrne approved these changes

2021-12-14 19:34 UTC, merged