Appium long press
flagpolejs/flagpole pull request #198
Opened 2021-12-07 15:10 UTC by ncalaway

Long press for a given number of milliseconds on the midpoint of an element.

2021-12-07 15:21 UTC, ncalaway commented
This is a candidate for standardization. We may want to include longpress functionality with browser testing. Thoughts?

2021-12-07 16:52 UTC, ncalaway commented
It's been so long that I forgot I already added longPress to the iValue interface.

2021-12-13 15:55 UTC, jasonbyrne requested changes

2021-12-13 15:58 UTC, ncalaway commented on src/appium/appiumelement.ts
> +    if (!boundsRes) return "Error: element bounds not acquired";
Changed

2021-12-14 19:28 UTC, jasonbyrne approved these changes

2021-12-14 19:40 UTC, merged