Appium set device properties
flagpolejs/flagpole pull request #201
Opened 2021-12-07 15:12 UTC by ncalaway

Get and set networking properties on a mobile device

2021-12-07 15:19 UTC, ncalaway commented
This would probably be just for Appium. I know Puppeteer can test mobile devices in the sense that Chrome DevTools can render different sizes for different devices. However, the devices in DevTools are really just different sized viewports, without anything else to them. Correct me if I'm wrong.

2021-12-15 03:24 UTC, jasonbyrne requested changes
I would like the scenario.set stuff to be removed

2021-12-15 03:24 UTC, jasonbyrne commented on src/appium/appium-helpers.ts
> +    scenario.set("capabilities", capabilities);
I'm really not a fan of setting these session-level variables

2021-12-17 14:11 UTC, jasonbyrne approved these changes

2021-12-17 14:14 UTC, jasonbyrne requested changes

2021-12-17 14:14 UTC, jasonbyrne commented on src/appium/appium-helpers.ts
> +  console.log(devProperties);
Should remove these console logs

2021-12-17 14:14 UTC, jasonbyrne commented on src/appium/appium-helpers.ts
> +    scenario.set("capabilities", capabilities);
Shouldn't these `scenario.set`s be removed?

2021-12-17 14:14 UTC, jasonbyrne commented on src/appium/appiumresponse.ts
> +    console.log("hello");
What's this for?

2021-12-17 20:02 UTC, jasonbyrne approved these changes

2021-12-17 20:02 UTC, merged